"""Plotting and XAI visualization settings (parity, attention, periodic table, histograms)."""

VISUALIZATION_CONFIG = {
    'figsize': (10, 10),
    'dpi': 800,
    'palette': {'Train': '#59a6c7', 'Test': '#d9534f', 'Validation': '#b8d5a8'},
    'scatter_alpha': 0.9,
    'hist_alpha': 0.7,
    'scatter_size': 55,
    'scatter_edge_width': 0.35,
    'parity_marginal_color': '#ffffff',
    'parity_marginal_hatch': '//',
    'parity_marginal_edgecolor': 'black',
    'parity_marginal_edge_width': 0.5,
    'legend_framealpha': 0.82,
    'parity_axis_lo': -1.5,
    'parity_axis_hi': 7.0,
    'parity_axis_ticks': (0, 2, 4, 6),
    'parity_font_size_label': 22,
    'parity_font_size_tick': 22,
    # Parity-plot ion colors (ion -> color); ion_type_order controls legend order
    'ion_type_order': ['Li', 'Mg', 'Ca', 'Na', 'Zn', 'K', 'Y', 'Al', 'Cs', 'Rb'],
    'ion_type_palette': {
        'Li': '#b5cdee',
        'Mg': '#b7d4b5',
        'Ca': '#56B4E9',
        'Na': '#1ce3b1',
        'Zn': '#f0e77f',
        'K': '#0692ea',
        'Y': '#f1a96f',
        'Al': '#CC79A7',
        'Cs': '#999999',
        'Rb': '#f4c7d3',
    },
    'attention_samples_to_plot': ['LiCoO2',
    ],
    'num_random_samples_per_element': 1,
    'font_family': 'Times New Roman',
    'font_size_title': 18,
    'font_size_label': 18,
    'font_size_legend': 16,
    'font_size_tick': 18,
    'calculate_global_attention_importance': True,
    'calculate_per_head_attention_importance': True,
    'save_per_layer_per_head_attention_heatmaps': False,
    'periodic_table_figsize_width': 16,
    'periodic_table_figsize_height': 8,
    'decoder_token_hist_figsize_width': 12,
    'decoder_token_hist_figsize_height': 10,
    'xai_periodic_table_cmap': 'viridis',
    'xai_periodic_table_missing_color': '#eaeaea',
    'xai_periodic_table_cell_alpha': 0.7,
    'xai_periodic_table_cell_size': 1.0,
    'xai_periodic_table_cell_gap': 0.08,
    'xai_periodic_table_fontsize_symbol': 22,
    'xai_periodic_table_fontsize_value': 14,
    'xai_periodic_table_colorbar_data_rect': [2.5, 8.20, 9.0, 0.30],
    'xai_periodic_table_title_gap_above_cbar': 0.05,
    'xai_periodic_table_colorbar_ticksize': 16,
    'xai_periodic_table_title_fontsize': 18,
    'xai_histogram_color_hi': '#e9b539',
    'xai_histogram_color_lo': '#d0d3d4',
    'xai_histogram_axis_linewidth': 2.4,
    'xai_histogram_top_k_default': 15,
    'xai_histogram_title_fontsize': 28,
    'xai_histogram_label_fontsize': 28,
    'xai_histogram_tick_fontsize': 28,
    'plot_training_curves_enabled': False,
    'plot_learning_rate_enabled': False,
}
